name: Decorations
main: Xenophilicy\Decorations\Decorations
version: 1.1.0
api: 3.0.0
author: Xenophilicy
softdepend:
  - EconomyAPI
permissions:
  decorations:
    children:
      decorations.menu:
        description: Allows use of the Decorations command and UI
        default: true
      decorations.override:
        description: Allows management of another player's spawned decorations
        default: op
